// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Landing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"bg-black h-screen\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>WAGGIS</title><link href=\"https://fonts.googleapis.com/css?family=Inconsolata&display=swap\" rel=\"stylesheet\"><script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script><script src=\"/static/grid.js\"></script><script src=\"/static/encom-globe.js\"></script><link href=\"/static/styles.css\" rel=\"stylesheet\"></head><body class=\"bg-black h-screen font-mono\"><div id=\"waggis-container\" class=\"fixed inset-0 flex items-center justify-center\"><span id=\"waggis-text\" class=\"text-white font-bold text-6xl font-mono tracking-widest transition-all duration-700\" style=\"transform: translateY(0);\"></span></div><div id=\"main-content\" class=\"flex flex-col items-center justify-center opacity-0 transition-opacity duration-700 mt-20\"><div class=\"text-white text-lg text-center\">I'm a 22 year-old developer<br>who uses <span class=\"text-green-400\">Node.JS</span>, <span class=\"text-blue-400\">Flutter</span>, <span class=\"text-orange-400\">HTML/CSS/JS</span>, and <span class=\"text-yellow-400\">others</span>.<br><br><span>Check out my <a href=\"https://github.com/joaofreitas21/waggis\" class=\"text-gray-300 underline\">GitHub</a> and <span class=\"text-gray-300 underline\">Twitter</span>.</span><br><br>I was last seen working on <span class=\"text-gray-300\">Mogul Merch</span>.<br>Business inquiry? <span class=\"text-gray-300 underline\">Email me!</span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Globe().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script src=\"/static/animation.js\"></script><script src=\"/static/globe.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
